spring:
  ### 配置数据库的连接方式
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/home/lijiabin/soft/sqlite/sign.db
    username:
    password:
  ### sqlite需要自己配置连接方式
  jpa:
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  freemarker:
    request-context-attribute: request
    cache: false
  mvc:
    static-path-pattern: /static/**
